"""
Cross-checks the Python (ctypes) binding against C-computed reference
values for the SAME inputs (spec section 31 Milestone 10: "no numerical
disagreement with C fixture tests"). Both sides call the identical
compiled hdcd shared library, so any disagreement here can only be a
ctypes marshaling bug (struct layout, argtypes, memory layout) -- not a
statistical/algorithmic one, which the C test suite already covers.

fixture.json is generated by generate_fixture.c; regenerate it with:
    cc -std=c99 -Iinclude generate_fixture.c build/libhdcd.a -lm -o /tmp/gen
    (cd python/tests && /tmp/gen)
"""

import ctypes
import json
import math
import os
import unittest
from ctypes import byref, c_double, c_size_t, c_void_p

import numpy as np

import hdcd
from hdcd import _capi
from hdcd._capi import HdcdLocalFitOptions, HdcdSinkhornOptions, check
from hdcd._model import Dag, DagFitResult, DependenceMatrix, Marginal, Topology

FIXTURE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixture.json")


def load_fixture():
    with open(FIXTURE_PATH) as f:
        return json.load(f)


class FixtureAgreementTests(unittest.TestCase):
    """Every check here drives the ctypes binding directly (not just
    hdcd.fit's high-level pipeline) and compares against fixture.json's
    C-computed values, so a struct-layout or argtypes mistake in
    hdcd/_capi.py would show up as a numeric mismatch here."""

    @classmethod
    def setUpClass(cls):
        cls.fixture = load_fixture()
        X = np.array(cls.fixture["X"], dtype=np.float64)  # (n, d), C order from JSON
        cls.X = np.asfortranarray(X)
        cls.n, cls.d = cls.X.shape
        cls.mask = np.asfortranarray(np.ones_like(cls.X, dtype=np.uint8))

    def test_marginal_sigma_cdf_logpdf_agree(self):
        eval_points = np.array(self.fixture["marginal_eval_points"], dtype=np.float64)
        for j in range(self.d):
            m = Marginal.fit(self.X[:, j], self.mask[:, j])
            self.assertAlmostEqual(m.sigma, self.fixture["marginal_sigma"][j], places=12)

            cdf = m.cdf(eval_points)
            np.testing.assert_allclose(cdf, self.fixture["marginal_cdf"][j], rtol=0, atol=1e-10)

            lp = m.logpdf(eval_points)
            np.testing.assert_allclose(lp, self.fixture["marginal_logpdf"][j], rtol=0, atol=1e-8)

    def test_copula_transform_agrees(self):
        U = self._transformed_U()
        expected = np.array(self.fixture["U_first_5_rows"], dtype=np.float64)
        np.testing.assert_allclose(U[:5, :], expected, rtol=0, atol=1e-10)

    def _transformed_U(self):
        marginals = [Marginal.fit(self.X[:, j], self.mask[:, j]) for j in range(self.d)]
        U = np.empty((self.n, self.d), dtype=np.float64, order="F")
        for j in range(self.d):
            x_col = np.ascontiguousarray(self.X[:, j])
            mask_col = np.ascontiguousarray(self.mask[:, j])
            u_col = np.empty(self.n, dtype=np.float64)
            check(_capi.lib.hdcd_transform_to_copula(
                marginals[j]._ptr, _capi._dptr(x_col), _capi._u8ptr(mask_col),
                c_size_t(self.n), c_double(0.0), _capi._dptr(u_col),
            ))
            U[:, j] = u_col
        return U

    def test_dependence_matrix_agrees(self):
        U = self._transformed_U()
        dm = DependenceMatrix.compute(U, self.mask)
        expected = np.array(self.fixture["dependence_matrix"], dtype=np.float64)
        np.testing.assert_allclose(dm.to_numpy(), expected, rtol=0, atol=1e-10)

    def test_topology_ordering_and_mst_agree(self):
        U = self._transformed_U()
        dm = DependenceMatrix.compute(U, self.mask)
        topo = Topology.compute(dm)

        np.testing.assert_array_equal(topo.ordering(), np.array(self.fixture["topology_ordering"]))

        expected_edges = self.fixture["topology_mst_edges"]
        actual_edges = topo.mst_edges()
        self.assertEqual(len(actual_edges), len(expected_edges))
        for (aj, ak, aw), (ej, ek, ew) in zip(actual_edges, expected_edges):
            self.assertEqual((aj, ak), (ej, ek))
            self.assertAlmostEqual(aw, ew, places=10)

    def test_dag_fit_holdout_scores_and_joint_log_density_agree(self):
        U = self._transformed_U()
        dag = Dag.create(self.d, 2)
        for parent, child in self.fixture["dag_edges"]:
            dag.add_edge(parent, child)

        # This struct is the highest-risk marshaling surface in the
        # whole binding: it's nested (HdcdLocalFitOptions contains
        # HdcdSinkhornOptions) and mixes size_t/double/uint64_t fields,
        # exactly where padding/alignment mistakes would silently
        # corrupt values instead of crashing.
        sinkhorn_options = HdcdSinkhornOptions(n_quadrature_nodes=0, tol=0.0, max_iterations=0)
        options = HdcdLocalFitOptions(
            bernstein_degree=3, lambda_roughness=0.15, holdout_fraction=0.25,
            seed=777, theta_max_iterations=0, theta_tol=0.0,
            sinkhorn_options=sinkhorn_options,
        )

        dag_fit = DagFitResult.fit(U, self.mask, dag, options)
        self.assertTrue(dag_fit.all_converged)

        expected_scores = self.fixture["dag_fit_holdout_scores"]
        for j in range(self.d):
            self.assertAlmostEqual(dag_fit.node(j).holdout_score, expected_scores[j], places=10)

        point = np.array(self.fixture["joint_log_density_point"], dtype=np.float64)
        value = dag_fit.joint_log_density(point)
        self.assertAlmostEqual(value, self.fixture["joint_log_density_value"], places=10)

        self.assertAlmostEqual(dag_fit.kl_estimate_, self.fixture["kl_estimate"], places=10)


class HighLevelApiSmokeTests(unittest.TestCase):
    """Exercises hdcd.fit's full pipeline (the documented spec section
    25 API), not just individual ctypes calls -- catches integration
    bugs the per-function fixture tests above wouldn't (e.g. wrong
    argument order when composing calls in _model.py)."""

    @classmethod
    def setUpClass(cls):
        fixture = load_fixture()
        cls.X = np.array(fixture["X"], dtype=np.float64)

    def test_fit_transform_logpdf_roundtrip(self):
        model = hdcd.fit(
            self.X, max_parents=2, bernstein_degree=3, lambda_edge=0.05,
            lambda_roughness=0.15, annealing_iterations=60, seed=1,
        )
        self.assertEqual(model.d, 3)

        U = model.transform(self.X)
        self.assertTrue(np.all(U > 0) and np.all(U < 1))

        clp = model.copula_logpdf(U)
        lp = model.logpdf(self.X)
        self.assertTrue(np.all(np.isfinite(clp)))
        self.assertTrue(np.all(np.isfinite(lp)))

        dm = model.dependence_matrix_
        self.assertEqual(dm.shape, (3, 3))
        with self.assertRaises(ValueError):
            dm[0, 0] = 5.0  # read-only (spec section 25)

        ordering = model.ordering_
        self.assertEqual(sorted(ordering.tolist()), [0, 1, 2])

        edges = model.dag_
        self.assertIsInstance(edges, tuple)

    def test_fit_dag_kl_comparison(self):
        model = hdcd.fit(self.X, max_parents=2, bernstein_degree=3, annealing_iterations=60, seed=2)
        result = model.fit_dag([])  # independence hypothesis
        self.assertIsInstance(result.kl_divergence_, float)
        self.assertFalse(math.isnan(result.kl_divergence_))

    def test_sample_not_implemented(self):
        model = hdcd.fit(self.X, max_parents=2, annealing_iterations=30, seed=3)
        with self.assertRaises(NotImplementedError):
            model.sample(10)

    def test_missing_data_handled_via_mask(self):
        X = self.X.copy()
        X[0, 0] = np.nan
        X[5, 1] = np.nan
        model = hdcd.fit(X, max_parents=2, annealing_iterations=30, seed=4)
        lp = model.logpdf(X)
        self.assertTrue(np.isnan(lp[0]))  # row 0 has a missing entry
        self.assertTrue(np.isnan(lp[5]))
        self.assertTrue(np.all(np.isfinite(np.delete(lp, [0, 5]))))


if __name__ == "__main__":
    unittest.main()
